name: Deploy Delima VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            -   name: Pull latest code
                run: |
                    cd /opt/delima
                    git pull origin main
            
            -   name: Reload Docker Container
                run: | 
                    cd /opt/delima
                    docker compose down
                    docker compose up -d --build
